# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu 16.04'
  demands: npm

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script:
      npm install
      npm run build --prod
    displayName: '⦿ Lint done & Karma tests is done & [PROD - Build] ➡ Finished ✔'

  - script:
      ls
    displayName: '⦿⦿⦿⦿⦿⦿⦿⦿⦿⦿⦿⦿⦿⦿'
    
  - task: ArchiveFiles@1
    displayName: 'Archive files'
    inputs:
      rootFolder: '$(System.DefaultWorkingDirectory)' #name of your project on angular.json .defaultProject value
      includeRootFolder: false

  - task: CopyFiles@2
    displayName: 'Copy File to: $(TargetFolder)'
    inputs:
      SourceFolder: '$(Build.ArtifactStagingDirectory)'
      Contents: '$(Build.BuildId).zip'
      TargetFolder: '$(Build.ArtifactStagingDirectory)\ArtifactsToBePublished'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)\ArtifactsToBePublished'
