# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: npm run lint 
  displayName: 'Lint done'
  
 - script: npm run test
  displayName: 'Karma tests is done'

- script: npm run prod-build-dev
   displayName: ' ⦿ [PROD - Build] ➡ Finished ✔'
