# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu 16.04'
  demands: npm

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script:
      npm install
      npm run build --prod
    displayName: '⦿ Lint done & Karma tests is done & [PROD - Build] ➡ Finished ✔'

  - script:
      ls
    displayName: '⦿⦿⦿⦿⦿⦿⦿⦿⦿⦿⦿⦿⦿⦿'

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(System.DefaultWorkingDirectory)/dist'
      contents: |
        **/*
      targetFolder: '$(Build.ArtifactStagingDirectory)'
      overWrite: true
    displayName: 'Copying built static files'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)\ArtifactsToBePublished'
